/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.cecar.vista;

import javax.swing.JOptionPane;
import javax.swing.border.MatteBorder;

/**
 *
 * @author Casalg
 */
public class Loging extends Principal {

    /**
     * Creates new form Loging
     */
    public Loging() {
        initComponents();
        
    }
    Enviar e = new Enviar();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbclave = new javax.swing.JLabel();
        txtmail = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        jlbcredenciales = new javax.swing.JLabel();
        jbtregistro = new javax.swing.JButton();
        jbtentrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 204)));
        setLayout(null);

        jlbclave.setBackground(new java.awt.Color(204, 204, 255));
        jlbclave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlbclave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbclave.setText("Ingresar Clave");
        jlbclave.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        add(jlbclave);
        jlbclave.setBounds(30, 130, 440, 24);

        txtmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtmail.setForeground(new java.awt.Color(0, 204, 255));
        txtmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtmail.setText("correo,telefono");
        txtmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        txtmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmailActionPerformed(evt);
            }
        });
        add(txtmail);
        txtmail.setBounds(30, 80, 440, 32);

        txtpassword.setForeground(new java.awt.Color(0, 204, 255));
        txtpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        add(txtpassword);
        txtpassword.setBounds(30, 170, 440, 35);

        jlbcredenciales.setBackground(new java.awt.Color(204, 204, 255));
        jlbcredenciales.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlbcredenciales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbcredenciales.setText("Ingresar Credenciales");
        jlbcredenciales.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        add(jlbcredenciales);
        jlbcredenciales.setBounds(30, 50, 440, 24);

        jbtregistro.setBackground(new java.awt.Color(153, 204, 255));
        jbtregistro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtregistro.setForeground(new java.awt.Color(51, 51, 51));
        jbtregistro.setText("Crear Cuenta");
        jbtregistro.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 153, 255)));
        jbtregistro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtregistroActionPerformed(evt);
            }
        });
        add(jbtregistro);
        jbtregistro.setBounds(90, 230, 90, 40);

        jbtentrar.setBackground(new java.awt.Color(153, 204, 255));
        jbtentrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtentrar.setForeground(new java.awt.Color(51, 51, 51));
        jbtentrar.setText("Entrar");
        jbtentrar.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 153, 255)));
        jbtentrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtentrarActionPerformed(evt);
            }
        });
        add(jbtentrar);
        jbtentrar.setBounds(330, 230, 90, 39);

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Iniciar Sesión");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void txtmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmailActionPerformed

    private void jbtregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtregistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtregistroActionPerformed

    private void jbtentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtentrarActionPerformed
        // TODO add your handling code here:
     txtmail.getText();
     txtpassword.getPassword();
        if (txtmail.isValid()) {
            if (txtpassword.isValid()) {
               e.setVisible(true);
            } else {
             System.err.println("Contraseña Errada");    
            }
            
        } else {
            System.err.println("Correo No Existe"+"/n"+"Crear Correo"); 
        }
     
    }//GEN-LAST:event_jbtentrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtentrar;
    private javax.swing.JButton jbtregistro;
    private javax.swing.JLabel jlbclave;
    private javax.swing.JLabel jlbcredenciales;
    private javax.swing.JTextField txtmail;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables

    private void setBorder(MatteBorder createMatteBorder) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
